# Generated by Django 3.0.4 on 2020-03-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_per_100ml',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_abv',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='brewer',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
